### ISSUE TITLE
How can I run the program to produce a OD1NF1ST Interactive Web Display? Thank you!

### ISSUE THREAD

**Issue by 1939552724** [MichaelWrana/OD1NF1ST#2]
Thank you for your code sharing about OD1NF1ST in URL https://github.com/MichaelWrana/OD1NF1ST. I have some questions about how to run the program and produce a OD1NF1ST Interactive Web Display.
1)	I have read the paper OD1NF1ST: True Skip Intrusion Detection and Avionics Network Cyber-Atack Simulation. When I run the command “python -m odf.web”and type http://127.0.0.1:8572/ in the browser, Fig.3 can be shown after I click the “START” button. However, Fig.3 is different from Fig.4(Interactive Web Display). So how can I get the Interactive Web Display like Fig.4?  Below are the screenshots of what I do according to your instructions.

![python_m_odf_web](https://user-images.githubusercontent.com/53972901/205875018-81389327-20e2-44d4-ad6d-b77b24870c28.JPG)
Fig.1 python -m odf.web
 
![127_0_0_1_8572](https://user-images.githubusercontent.com/53972901/205875165-fe0f2c02-322d-4a5c-ad85-ed99cc360902.JPG)
Fig.2 type http://127.0.0.1:8572/ in the browser
 
![click start](https://user-images.githubusercontent.com/53972901/205875312-8d9be8ef-44ff-4b6b-9c0f-427676e22deb.JPG)
Fig.3 after clicking the “START” button
 
![click start paper](https://user-images.githubusercontent.com/53972901/205875375-fd39fa9b-3d64-4ff1-8567-ad5a4ff1d61f.JPG)
Fig.4 Interactive Web Display
2)	I can succeed to run the subsystem “odf/ids”.
 
![ids_subsystem](https://user-images.githubusercontent.com/53972901/205875407-f4e3a1b8-52f9-4ab4-a0e5-0536cb61857d.JPG)
Fig.5 IDS subsystem

**Comment by MichaelWrana** [comment]
The web display requires MSFS data.  This is not included in the repository due to file size limitations.  If you want to set up the full webpage you can 1) open MSFS and select an aircraft and flight plan 2) run `export SYS_LOG_EVENT=False && python -m odf.mfs`.  This will generate data used by the web display. 3) re-run `python -m odf.web` and your flight should appear in a list in figure 3.

**Comment by 1939552724** [comment]
Thank you for your help!



---Original---
From: "M ***@***.***&gt;
Date: Tue, Dec 6, 2022 21:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MichaelWrana/OD1NF1ST] How can I run the program to produce aOD1NF1ST Interactive Web Display? Thank you! (Issue #2)




 
The web display requires MSFS data.  This is not included in the repository due to file size limitations.  If you want to set up the full webpage you can 1) open MSFS and select an aircraft and flight plan 2) run export SYS_LOG_EVENT=False &amp;&amp; python -m odf.mfs.  This will generate data used by the web display. 3) re-run python -m odf.web and your flight should appear in a list in figure 3.
